spring:
  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${spring.security.oauth2.client.registration.kakao.client-id}
            client-secret: ${spring.security.oauth2.client.registration.kakao.client-secret}
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: ${spring.security.oauth2.client.registration.kakao.authorization-grant-type}
            redirect-uri: ${spring.security.oauth2.client.registration.kakao.redirect-uri}
            client-name: ${spring.security.oauth2.client.registration.kakao.client-name}
            client-authentication-method: ${spring.security.oauth2.client.registration.kakao.client-authentication-method}

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${jwt.secret}
  access-token-validity-in-milliseconds: ${jwt.access-token-validity-in-milliseconds}
  refresh-token-validity-in-milliseconds: ${jwt.refresh-token-validity-in-milliseconds}

ai:
  base-url: ${ai.base-url}
  chat-path: ${ai.chat-path}
  timeout:
    connect-ms: ${ai.timeout.connect-ms}
    read-ms: ${ai.timeout.read-ms}

cloud:
  aws:
    s3:
      bucket: ${cloud.aws.s3.bucket}
    region:
      static: ${cloud.aws.region.static}
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}